### ISSUE TITLE
Add Text Blob to Dependency

### ISSUE THREAD

**Issue by tlmurphy** [jmhossler/twitter-mood#4]
We need to add TextBlob as a dependency so that it comes installed when a user installs our package @jmhossler

**Comment by jmhossler** [comment]
https://github.com/jmhossler/twitter-mood/blob/master/setup.py#L23

It is a dependency. If you pip install it, it should install textblob.

**Comment by jmhossler** [comment]
Had the dependency in the incorrect place. Moved it. If you install 0.0.3, it should have texblob as a correct dependency
